language: node_js
node_js:
  - lts/*
  
install:
  - npm install coveralls --save-dev

cache:
  directories:
    - "node_modules"
    
script:
  - npm run lint
  - npm run test:coveralls
  
notification:
  email: false
