language: node_js
node_js:
  - lts/*

cache:
  directories:
    - "node_modules"

notification:
  email: false

before_install:

 -mysql -e 'DROP DATABASE IF EXISTS witsoverflow';
 -mysql -e 'CREATE DATABASE witsoverflow';

after_success:
  - ./node_modules/.bin/codecov --token="13ced673-3e19-42ec-bc41-7ce35816e908"
